In [4]:
import requests
import pandas as pd
from datetime import datetime, timedelta

# Set your date range (last 30 days as an example)
end_time = datetime.utcnow()
start_time = end_time - timedelta(days=30)

# Format date as YYYY-MM-DD
start_date = start_time.strftime('%Y-%m-%d')
end_date = end_time.strftime('%Y-%m-%d')

# USGS Earthquake API endpoint
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

# Define parameters
params = {
    "format": "geojson",
    "starttime": start_date,
    "endtime": end_date,
    "minmagnitude": 3.0,   # Change this if you want all quakes
    "orderby": "time"
}

# Send request
response = requests.get(url, params=params)
data = response.json()

# Parse data
records = []
for feature in data["features"]:
    props = feature["properties"]
    geometry = feature["geometry"]["coordinates"]

    record = {
        "time": datetime.utcfromtimestamp(props["time"] / 1000),
        "latitude": geometry[1],
        "longitude": geometry[0],
        "depth": geometry[2],
        "magnitude": props.get("mag", None),
        "place": props.get("place", None),
        "alert": props.get("alert", None),
        "status": props.get("status", None),
        "tsunami": props.get("tsunami", None),
        "type": props.get("type", None)
    }

    records.append(record)

# Save to CSV
df = pd.DataFrame(records)
df.to_csv("earthquake_metadata.csv", index=False)
print("✅ Earthquake metadata saved to earthquake_metadata.csv")

✅ Earthquake metadata saved to earthquake_metadata.csv

In [5]:
import pandas as pd

# Load the saved CSV
df = pd.read_csv("earthquake_metadata.csv")

# Show first 10 rows
df.head(10)

,time,latitude,longitude,depth,magnitude,place,alert,status,tsunami,type
0,2025-03-21 23:48:15.680,18.7998,-64.4158,8.000,3.96,"65 km NE of Cruz Bay, U.S. Virgin Islands",NaN,reviewed,0,earthquake
1,2025-03-21 20:02:57.690,-17.4952,-174.9070,253.107,4.60,"161 km NW of Neiafu, Tonga",NaN,reviewed,0,earthquake
2,2025-03-21 19:42:36.289,51.2881,-176.2937,43.251,4.50,"69 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake
3,2025-03-21 19:28:18.675,-8.6885,159.4498,10.000,5.00,"62 km SSW of Buala, Solomon Islands",NaN,reviewed,0,earthquake
4,2025-03-21 18:17:40.618,51.0171,-176.1418,30.158,3.80,"101 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake
5,2025-03-21 17:47:40.341,51.1930,-176.1381,34.627,4.60,"83 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake
6,2025-03-21 17:08:51.891,-7.1363,155.6402,87.025,4.90,"92 km S of Panguna, Papua New Guinea",NaN,reviewed,0,earthquake
7,2025-03-21 16:03:50.985,51.1272,-175.9864,16.300,3.70,"94 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake
8,2025-03-21 15:46:32.815,51.1558,-176.1139,32.230,4.60,"87 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake
9,2025-03-21 15:24:27.801,51.0954,-176.0432,16.900,3.60,"95 km SSE of Adak, Alaska",NaN,reviewed,0,earthquake

In [6]:
import pandas as pd

# Load data
df = pd.read_csv("earthquake_metadata.csv")

# Convert 'time' to datetime
df['time'] = pd.to_datetime(df['time'])

# Feature Engineering: Extract hour, weekday, night/weekend indicator
df['hour'] = df['time'].dt.hour
df['day_of_week'] = df['time'].dt.dayofweek
df['is_night'] = df['hour'].apply(lambda x: 1 if x < 6 or x > 20 else 0)
df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

# Fill missing values
df['alert'] = df['alert'].fillna('none')
df['depth'] = df['depth'].fillna(df['depth'].median())
df['magnitude'] = df['magnitude'].fillna(df['magnitude'].median())

# Create a binary label column: 1 = high risk, 0 = low risk
# You can tweak the thresholds here as you like
df['early_warning_risk'] = df.apply(lambda row: 1 if (row['magnitude'] >= 4.5 and row['depth'] <= 30) else 0, axis=1)

# Drop irrelevant columns if you want (optional)
# df = df.drop(columns=['status', 'tsunami', 'type'])

# Show result
df.head()

,time,latitude,longitude,depth,magnitude,place,alert,status,tsunami,type,hour,day_of_week,is_night,is_weekend,early_warning_risk
0,2025-03-21 23:48:15.680,18.7998,-64.4158,8.000,3.96,"65 km NE of Cruz Bay, U.S. Virgin Islands",none,reviewed,0,earthquake,23,4,1,0,0
1,2025-03-21 20:02:57.690,-17.4952,-174.9070,253.107,4.60,"161 km NW of Neiafu, Tonga",none,reviewed,0,earthquake,20,4,0,0,0
2,2025-03-21 19:42:36.289,51.2881,-176.2937,43.251,4.50,"69 km SSE of Adak, Alaska",none,reviewed,0,earthquake,19,4,0,0,0
3,2025-03-21 19:28:18.675,-8.6885,159.4498,10.000,5.00,"62 km SSW of Buala, Solomon Islands",none,reviewed,0,earthquake,19,4,0,0,1
4,2025-03-21 18:17:40.618,51.0171,-176.1418,30.158,3.80,"101 km SSE of Adak, Alaska",none,reviewed,0,earthquake,18,4,0,0,0

In [7]:
# Save preprocessed data to CSV
df.to_csv("earthquake_metadata_preprocessed.csv", index=False)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

# Encode categorical features (alert column)
df['alert_encoded'] = LabelEncoder().fit_transform(df['alert'])

# Define features and target
features = ['latitude', 'longitude', 'depth', 'magnitude', 'hour', 'day_of_week', 'is_night', 'is_weekend', 'alert_encoded']
X = df[features]
y = df['early_warning_risk']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "DecisionTree": DecisionTreeClassifier(max_depth=5, random_state=42),
    "LogisticRegression": LogisticRegression(max_iter=1000)
}

# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"\n📊 Model: {name}")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

📊 Model: KNN
[[160  23]
 [ 19  27]]
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       183
           1       0.54      0.59      0.56        46

    accuracy                           0.82       229
   macro avg       0.72      0.73      0.72       229
weighted avg       0.82      0.82      0.82       229


📊 Model: DecisionTree
[[183   0]
 [  0  46]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       183
           1       1.00      1.00      1.00        46

    accuracy                           1.00       229
   macro avg       1.00      1.00      1.00       229
weighted avg       1.00      1.00      1.00       229


📊 Model: LogisticRegression
[[177   6]
 [  2  44]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       183
           1       0.88      0.96      0.92        46

    accuracy                           0.97       229
   macro avg       0.93      0.96      0.95       229
weighted avg       0.97      0.97      0.97       229

In [2]:
# logistic_regression_train.py

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris  # Example dataset, replace with your own
import joblib

# Load dataset (replace this with your earthquake metadata dataset)
X, y = load_iris(return_X_y=True)  # For demo purpose
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define Logistic Regression model
logreg = LogisticRegression()

# Train the model
logreg.fit(X_train, y_train)

# Save the model
joblib.dump(logreg, 'logistic_regression_model.pkl')
print("✅ Logistic Regression model trained and saved as 'logistic_regression_model.pkl'")

✅ Logistic Regression model trained and saved as 'logistic_regression_model.pkl'

In [3]:
import joblib

# Assuming your trained Logistic Regression model is in a variable called `logreg`
joblib.dump(logreg, "logistic_regression_model.pkl")

['logistic_regression_model.pkl']

In [5]:
import shutil
shutil.move("logistic_regression_model.pkl", "logistic_regression_model.pkl")

'logistic_regression_model.pkl'

In [6]:
!pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.115.11-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting starlette<0.47.0,>=0.40.0 (from fastapi)
  Downloading starlette-0.46.1-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from fastapi) (2.10.6)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from fastapi) (4.12.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (8.1.8)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.27.2)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.11/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (1.3.1)
Downloading fastapi-0.115.11-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 7.2 MB/s eta 0:00:00
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.6 MB/s eta 0:00:00
Downloading starlette-0.46.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.7 MB/s eta 0:00:00
Installing collected packages: uvicorn, starlette, fastapi
Successfully installed fastapi-0.115.11 starlette-0.46.1 uvicorn-0.34.0

In [7]:
from fastapi import FastAPI, Request
from pydantic import BaseModel
import joblib
import numpy as np

# Load the saved model
model = joblib.load("logistic_regression_model.pkl")

# Define the FastAPI app
app = FastAPI()

# Define the input schema
class PredictionInput(BaseModel):
    features: list  # Expecting a list of feature values

@app.post("/predict")
def predict(data: PredictionInput):
    features = np.array(data.features).reshape(1, -1)
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features).tolist()[0] if hasattr(model, "predict_proba") else None
    return {
        "prediction": int(prediction),
        "probability": probability
    }

In [20]:
# Replace YOUR_AUTHTOKEN_HERE with your actual token
!ngrok config add-authtoken 2uP4GOwyErnfdYCTvHztswwCBik_211Bj55XCknmezq5DHryx

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [21]:
!pip install fastapi uvicorn nest_asyncio pyngrok

import nest_asyncio
import uvicorn
from pyngrok import ngrok
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import joblib
import numpy as np

nest_asyncio.apply()

# Load model
model = joblib.load("logistic_regression_model.pkl")

# Define app
app = FastAPI()

class PredictionInput(BaseModel):
    features: list

@app.post("/predict")
def predict(data: PredictionInput):
    try:
        features = np.array(data.features).reshape(1, -1)
        prediction = int(model.predict(features)[0])
        try:
            probability = model.predict_proba(features).tolist()[0]
        except:
            probability = None

        return {
            "prediction": prediction,
            "probability": probability
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")

# Expose via ngrok
public_url = ngrok.connect(8000)
print(f"🔗 Public URL: {public_url}")

# Start FastAPI server
uvicorn.run(app, host="0.0.0.0", port=8000)

Requirement already satisfied: fastapi in /usr/local/lib/python3.11/dist-packages (0.115.11)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.11/dist-packages (0.34.0)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.11/dist-packages (1.6.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.11/dist-packages (7.2.3)
Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from fastapi) (0.46.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from fastapi) (2.10.6)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from fastapi) (4.12.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (8.1.8)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (0.14.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.11/dist-packages (from pyngrok) (6.0.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.27.2)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.11/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (1.3.1)
🔗 Public URL: NgrokTunnel: "https://b289-34-106-214-52.ngrok-free.app" -> "http://localhost:8000"

INFO:     Started server process [878]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [878]

In [8]:
import requests

def fetch_usgs_metadata():
    url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson"
    response = requests.get(url)
    data = response.json()

    events = []
    for feature in data["features"]:
        props = feature["properties"]
        event = {
            "magnitude": props["mag"],
            "depth": feature["geometry"]["coordinates"][2],
            "latitude": feature["geometry"]["coordinates"][1],
            "longitude": feature["geometry"]["coordinates"][0],
            "place": props["place"],
            "time": props["time"]
        }
        events.append(event)

    return events

In [9]:
import requests

def send_to_prediction_api(event):
    # You need to prepare features list exactly as required by the model
    features = [event['magnitude'], event['depth'], event['latitude'], event['longitude']]  # Example: 4 features

    response = requests.post(
        "http://127.0.0.1:8000/predict",
        json={"features": features}
    )

    if response.status_code == 200:
        return response.json()
    else:
        print("Prediction API Error:", response.text)
        return None

In [10]:
!apt install cloudflared

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cloudflared

In [11]:
import nest_asyncio
import uvicorn
nest_asyncio.apply()

uvicorn.run(app, host="0.0.0.0", port=8000)

INFO:     Started server process [724]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [724]

In [12]:
# ✅ Download and install cloudflared manually
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!mv cloudflared-linux-amd64 cloudflared
!chmod +x cloudflared

--2025-03-22 14:27:09--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64 [following]
--2025-03-22 14:27:09--  https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/106867604/eac8237f-c554-46b5-95ea-f2f5873e69a5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250322T142709Z&X-Amz-Expires=300&X-Amz-Signature=9b19ea094ec1859dfa2c0326c001b6d1cb5400b310668126f247cc8d53ec4a95&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2025-03-22 14:27:09--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/106867604/eac8237f-c554-46b5-95ea-f2f5873e69a5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250322T142709Z&X-Amz-Expires=300&X-Amz-Signature=9b19ea094ec1859dfa2c0326c001b6d1cb5400b310668126f247cc8d53ec4a95&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37844205 (36M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  36.09M  --.-KB/s    in 0.1s

2025-03-22 14:27:09 (350 MB/s) - ‘cloudflared-linux-amd64’ saved [37844205/37844205]

In [13]:
# Kill existing server if any
!fuser -k 8000/tcp

# Run FastAPI app
from fastapi import FastAPI
import nest_asyncio
import uvicorn
from threading import Thread

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello from Cloudflare Tunnel!"}

nest_asyncio.apply()

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = Thread(target=run)
thread.start()

In [1]:
# Run FastAPI app
from fastapi import FastAPI
import nest_asyncio
import uvicorn
from threading import Thread

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello from Cloudflare Tunnel!"}

nest_asyncio.apply()

# Kill existing process on port 8000 (important fix!)
!fuser -k 8000/tcp

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = Thread(target=run)
thread.start()

In [1]:
# Run FastAPI app
from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
import uvicorn
from threading import Thread
import joblib  # for loading ML model

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello from Cloudflare Tunnel!"}

# -----------------------
# Define input data schema
class MetadataInput(BaseModel):
    mag: float
    depth: float
    latitude: float
    longitude: float

# Load your trained ML model
model = joblib.load("earthquake_model.pkl")  # Replace with your actual model file

@app.post("/predict")
def predict(input_data: MetadataInput):
    features = [[
        input_data.mag,
        input_data.depth,
        input_data.latitude,
        input_data.longitude
    ]]
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0].max()

    return {
        "earthquake_likelihood": "Yes" if prediction == 1 else "No",
        "confidence_score": round(probability, 3)
    }

nest_asyncio.apply()

# Kill existing process on port 8000
!fuser -k 8000/tcp

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = Thread(target=run)
thread.start()

In [1]:
# Run FastAPI app
from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
import uvicorn
from threading import Thread
import joblib  # for loading ML model

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello from Cloudflare Tunnel!"}

# -----------------------
# Define input data schema
class MetadataInput(BaseModel):
    mag: float
    depth: float
    latitude: float
    longitude: float

# Load your trained ML model
model = joblib.load("earthquake_model.pkl")  # Replace with your actual model file

@app.post("/predict")
def predict(input_data: MetadataInput):
    features = [[
        input_data.mag,
        input_data.depth,
        input_data.latitude,
        input_data.longitude
    ]]
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0].max()

    return {
        "earthquake_likelihood": "Yes" if prediction == 1 else "No",
        "confidence_score": round(probability, 3)
    }

nest_asyncio.apply()

# Kill existing process on port 8000
!fuser -k 8000/tcp

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = Thread(target=run)
thread.start()

In [2]:
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

--2025-03-22 14:30:55--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64 [following]
--2025-03-22 14:30:55--  https://github.com/cloudflare/cloudflared/releases/download/2025.2.1/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/106867604/eac8237f-c554-46b5-95ea-f2f5873e69a5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250322T143055Z&X-Amz-Expires=300&X-Amz-Signature=977930ef1db27ffdc7d547ec7641c48a23e978415d7d9964a5734b2ebdf82f78&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2025-03-22 14:30:55--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/106867604/eac8237f-c554-46b5-95ea-f2f5873e69a5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250322T143055Z&X-Amz-Expires=300&X-Amz-Signature=977930ef1db27ffdc7d547ec7641c48a23e978415d7d9964a5734b2ebdf82f78&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37844205 (36M) [application/octet-stream]
Saving to: ‘cloudflared’

cloudflared         100%[===================>]  36.09M  --.-KB/s    in 0.1s

2025-03-22 14:30:56 (347 MB/s) - ‘cloudflared’ saved [37844205/37844205]

In [3]:
!./cloudflared tunnel --url http://localhost:8000

2025-03-22T14:30:58Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2025-03-22T14:30:58Z INF Requesting new quick Tunnel on trycloudflare.com...
2025-03-22T14:31:03Z INF +--------------------------------------------------------------------------------------------+
2025-03-22T14:31:03Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2025-03-22T14:31:03Z INF |  https://grove-removal-hopes-simplified.trycloudflare.com                                  |
2025-03-22T14:31:03Z INF +--------------------------------------------------------------------------------------------+
2025-03-22T14:31:03Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2025-03-22T14:31:03Z INF Version 2025.2.1 (Checksum afdfadd1ef552e66bffc35246fe30a9bd578356d2d386de95585ccfc432472b8)
2025-03-22T14:31:03Z INF GOOS: linux, GOVersion: go1.22.10, GoArch: amd64
2025-03-22T14:31:03Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8000]
2025-03-22T14:31:03Z INF Generated Connector ID: c5ea051d-2b26-4e63-990d-4735e302a1e4
2025-03-22T14:31:03Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/as-a-service/
2025-03-22T14:31:03Z INF Initial protocol quic
2025-03-22T14:31:03Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2025-03-22T14:31:03Z INF ICMP proxy will use :: as source for IPv6
2025-03-22T14:31:03Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2025-03-22T14:31:03Z INF ICMP proxy will use :: as source for IPv6
2025-03-22T14:31:03Z INF Starting metrics server on 127.0.0.1:20241/metrics
2025-03-22T14:31:03Z INF Using [CurveID(4588) CurveID(25497) CurveP256] as curve preferences connIndex=0 event=0 ip=198.41.192.227
2025/03/22 14:31:03 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2025-03-22T14:31:03Z INF Registered tunnel connection connIndex=0 connection=35f1df52-7010-4bb0-8861-43364c77537e event=0 ip=198.41.192.227 location=iad09 protocol=quic
INFO:     54.86.50.139:0 - "POST /predict HTTP/1.1" 200 OK
2025-03-22T15:19:43Z INF Initiating graceful shutdown due to signal interrupt ...
^C

In [ ]:
import time
import requests

# ===================== CONFIGURATION =====================
PREDICT_API_URL = "http://resqbot.duckdns.org/"  # Replace this
CONFIDENCE_THRESHOLD = 0.7
CHECK_INTERVAL_SECONDS = 30
MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 10
# =========================================================

def fetch_latest_earthquake():
    # Placeholder: replace with real USGS fetch logic
    return {
        "mag": 3.2,
        "depth": 5.0,
        "latitude": 35.6895,
        "longitude": 139.6917
    }

def get_prediction_with_retry(earthquake_data):
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.post(PREDICT_API_URL, json=earthquake_data)
            if response.status_code == 200:
                return response.json()
            else:
                print(f"❌ Prediction API error: {response.status_code}")
                if response.status_code >= 500 and attempt < MAX_RETRIES:
                    print(f"🔁 Retrying in {RETRY_DELAY_SECONDS}s... (Attempt {attempt}/{MAX_RETRIES})")
                    time.sleep(RETRY_DELAY_SECONDS)
                else:
                    break
        except Exception as e:
            print(f"⚠️ Prediction request failed: {e}")
            if attempt < MAX_RETRIES:
                print(f"🔁 Retrying in {RETRY_DELAY_SECONDS}s... (Attempt {attempt}/{MAX_RETRIES})")
                time.sleep(RETRY_DELAY_SECONDS)
            else:
                break
    return None

def trigger_alert(earthquake_data, prediction_data):
    print(f"🚨 ALERT TRIGGERED!")
    print(f"⚠️ Earthquake Likelihood: {prediction_data.get('earthquake_likelihood')}")
    print(f"📈 Confidence Score: {prediction_data.get('confidence_score')}")
    print(f"📍 Location: Lat {earthquake_data['latitude']}, Lon {earthquake_data['longitude']}, Mag {earthquake_data['mag']}")

def main():
    print("\n🌍 Real-time Earthquake Prediction Monitor Started...\n")
    while True:
        quake_data = fetch_latest_earthquake()
        print(f"✅ Fetched latest quake: {quake_data}")

        prediction = get_prediction_with_retry(quake_data)

        if prediction:
            if prediction.get("earthquake_likelihood") == "Yes":
                confidence = prediction.get("confidence_score", 0)
                if confidence >= CONFIDENCE_THRESHOLD:
                    trigger_alert(quake_data, prediction)
                else:
                    print(f"ℹ️ Prediction is 'Yes' but confidence {confidence} is below threshold.")
            else:
                print("✅ Prediction is 'No' or not high risk. No alert triggered.")
        else:
            print("❌ Failed to get valid prediction response after retries.")

        print("\n⏳ Waiting for next check...\n")
        time.sleep(CHECK_INTERVAL_SECONDS)

if __name__ == "__main__":
    main()

🌍 Real-time Earthquake Prediction Monitor Started...

✅ Fetched latest quake: {'mag': 3.2, 'depth': 5.0, 'latitude': 35.6895, 'longitude': 139.6917}
⚠️ Prediction request failed: HTTPConnectionPool(host='resqbot.duckdns.org', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7e5812b45f50>: Failed to resolve 'resqbot.duckdns.org' ([Errno -2] Name or service not known)"))
🔁 Retrying in 10s... (Attempt 1/3)
⚠️ Prediction request failed: HTTPConnectionPool(host='resqbot.duckdns.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7e5812b69410>, 'Connection to resqbot.duckdns.org timed out. (connect timeout=None)'))
🔁 Retrying in 10s... (Attempt 2/3)

In [8]:
# main.py
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message": "FastAPI is working"}